from dydx3.constants import API_HOST_GOERLI, API_HOST_MAINNET
from decouple import config

# !!!! SELECT MODE !!!! production = mainnet or develpment = testnet
MODE = "DEVELOPMENT"

# CLOSE ALL OPEN POSITIONS AND ORDERS
ABORT_ALL_POSITIONS = True

# FIND COINTEGRATED PAIRS
FIND_COINTEGRATED = True

# PLACE TRADES
PLACE_TRADES = True

# RESOLUTION
RESOLUTION = "1HOUR"

# STATS WINDOW
WINDOW = 21

# THRESHOLD - OPENING
MAX_HALF_LIFE = 24
ZSCORE_THRESH = 1.5
USD_PER_TRADE = 50
USD_MIN_COLLATERAL = 1880

# THRESHOLDS - CLOSING
CLOSE_AT_ZSCORE_CROSS = True

# ETHEREUM ADDRESS
ETHEREUM_ADDRESS = "0xFF89054884BdD24816BBd13159Ccf45915f95f0c"

# KEYS - PRODUCTION
# must be on  mainnet on DYDX
STARK_PRIVATE_KEY_MAINNET = ""
DYDX_API_KEY_MAINNET = ""
DYDX_API_SECRET_MAINNET = ""
DYDX_API_PASSPHRASE_MAINNET = ""

# KEYS - DEVELOPMENT
# must be on  testnet on DYDX
STARK_PRIVATE_KEY_TESTNET = config("STARK_PRIVATE_KEY_TESTNET")
DYDX_API_KEY_TESTNET = config("DYDX_API_KEY_TESTNET")
DYDX_API_SECRET_TESTNET = config("DYDX_API_SECRET_TESTNET")
DYDX_API_PASSPHRASE_TESTNET = config("DYDX_API_PASSPHRASE_TESTNET")

# KEYS - EXPORT
STARK_PRIVATE_KEY = STARK_PRIVATE_KEY_MAINNET if MODE == "PRODUCTION" else STARK_PRIVATE_KEY_TESTNET
DYDX_API_KEY = DYDX_API_KEY_MAINNET if MODE == "PRODUCTION" else DYDX_API_KEY_TESTNET
DYDX_API_SECRET = DYDX_API_SECRET_MAINNET if MODE == "PRODUCTION" else DYDX_API_SECRET_TESTNET
DYDX_API_PASSPHRASE = DYDX_API_PASSPHRASE_MAINNET if MODE == "PRODUCTION" else DYDX_API_PASSPHRASE_TESTNET

# HOST - EXPORT
HOST = API_HOST_MAINNET if MODE == "PRODUCTION" else API_HOST_GOERLI

# HTTP PROVIDER
HTTP_PROVIDER_MAINNET = "https://eth-mainnet.g.alchemy.com/v2/vhFXlIQYJZOuUAwjgkb9ljm45enBa7bu",
HTTP_PROVIDER_TESTNET = "https://eth-goerli.g.alchemy.com/v2/Z_3JP5Wiccx0-QdwW9pa8CiEHa28-TMX",
HTTP_PROVIDER = HTTP_PROVIDER_MAINNET if MODE == "PRODUCTION" else HTTP_PROVIDER_TESTNET